#!/bin/bash
echo lsblk  -o  NAME,KNAME,TYPE,MOUNTPOINT,MODE,SIZE,OWNER,GROUP,MIN-IO,OPT-IO,PHY-SEC,LOG-SEC,ROTA,SCHED,RQ-SIZE
lsblk  -o  NAME,KNAME,TYPE,MOUNTPOINT,MODE,SIZE,OWNER,GROUP,MIN-IO,OPT-IO,PHY-SEC,LOG-SEC,ROTA,SCHED,RQ-SIZE


